src/posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
  path('search/', views.search, name='search'),
  path('', views.post_comment_create_and_list_view, name='main-post-view'),
  path('myposts/', views.myposts, name='myposts'),
  path('liked/', views.like_unlike_post, name='like-post-view'),
  path('<pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
  path('<pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
]

src/profiles/urls.py
from django.urls import path
from .import views

app_name = 'profiles'

urlpatterns = [
  path('', views.ProfileListView.as_view(), name='all-profiles'),
  path('myprofile/', views.myprofile, name='myprofile'),
  path('my-invites/', views.inivites_received, name='my-invites'),
  path('to-invite/', views.inivite_profiles_list, name='invite-profiles'),
  path('send-invite/', views.send_invitation, name='send-invite'),  
  path('remove-friend/', views.remove_from_friends, name='remove-friend'),
  path('my-invites/accept/', views.accept_invitation, name='accept-invite'),
  path('my-invites/reject/', views.reject_invitation, name='reject-invite'),
  path('<slug>/', views.ProfileDetailView.as_view(), name='profile-detail'),
]

src/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from profiles.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),  
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('register/', register, name='register'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.urls import reverse
from sorl.thumbnail import ImageField

from .utils import get_random_code

class ProfileManager(models.Manager):
  def get_all_profiles_to_invite(self, sender):
    profiles = Profile.objects.all().exclude(user=sender)
    profile = Profile.objects.get(user=sender)
    qs = Relationship.objects.filter(
      Q(sender=profile) | Q(receiver=profile)
    )

    accepted = set([])
    for rel in qs:
      if rel.status == 'accepted':
        accepted.add(rel.receiver)
        accepted.add(rel.sender)

    available = [profile for profile in profiles if profile not in accepted]
    return available

  
  def get_all_profiles(self, me):
    profiles = Profile.objects.all().exclude(user=me)
    return profiles



class Profile(models.Model):
  first_name  = models.CharField(max_length=200, blank=True)
  last_name   = models.CharField(max_length=200, blank=True)
  user        = models.ForeignKey(User, on_delete=models.CASCADE)
  bio         = models.TextField(default='No bio...', max_length=300)
  email       = models.EmailField(blank=True)
  country     = models.CharField(max_length=200, blank=True)
  avatar      = ImageField(default='default.png', upload_to='avatars/')
  friends     = models.ManyToManyField(User, blank=True, related_name='friends')
  slug        = models.SlugField(unique=True, blank=True)
  updated     = models.DateTimeField(auto_now=True)
  created     = models.DateTimeField(auto_now_add=True)

  objects     = ProfileManager()   

  def __str__(self):
    return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

  def get_absolute_url(self):
    return reverse('profiles:profile-detail', kwargs={'slug': self.slug})

  def get_friends(self):
    return self.friends.all()

  def get_friends_num(self):
    return self.friends.all().count()
  
  def get_posts_num(self):
    return self.posts.all().count()

  def get_all_authors_posts(self):
    return self.posts.all()
  
  def get_likes_given_num(self):
    likes = self.like_set.all()
    total_liked = 0
    for item in likes:
      if item.value == 'Like':
        total_liked += 1
    return total_liked

  def get_likes_received_num(self):
    posts = self.posts.all()
    total_liked = 0
    for item in posts:
      total_liked += item.liked.all().count()
    return total_liked

  __initial_first_name = None
  __initial_last_name = None

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.__initial_first_name = self.first_name
    self.__initial_last_name = self.last_name

  def save(self, *args, **kwargs):
    ex = False
    to_slug = self.slug
    if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
      if self.first_name and self.last_name:
        to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
        ex = Profile.objects.filter(slug=to_slug).exists()
        while ex:
          to_slug = slugify(to_slug + "_" + str(get_random_code()))
          ex = Profile.objects.filter(slug=to_slug).exists()
      else:
        to_slug = str(self.user)
    self.slug = to_slug
    super().save(*args, **kwargs)

STATUS_CHOICES = (
  ('send', 'send'),
  ('accepted', 'accepted'),
)

class RelationshipManager(models.Manager):
  def invitations_received(self, receiver):
    qs = Relationship.objects.filter(receiver=receiver, status='send')
    return qs

class Relationship(models.Model):
  sender    = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
  receiver  = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
  status    = models.CharField(max_length=8, choices=STATUS_CHOICES)
  updated   = models.DateTimeField(auto_now=True)
  created   = models.DateTimeField(auto_now_add=True)

  objects   = RelationshipManager()

  def __str__(self):
    return f"{self.sender}-{self.receiver}-{self.status}"

src/profiles/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
  password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
  password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

  class Meta:
    model = User
    fields = ('username', 'first_name', 'email')

  def clean_password2(self):
    cd = self.cleaned_data
    if cd['password1'] != cd['password2']:
      raise forms.ValidationError('Passwords don\'t match.')
    return cd['password2']


class ProfileModelForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['first_name', 'last_name', 'bio', 'avatar']
    

src/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm, UserRegistrationForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


def register(request):
  if request.method == 'POST':
    user_form = UserRegistrationForm(request.POST)
    if user_form.is_valid():
      # Create a new user object but avoid saving it yet
      new_user = user_form.save(commit=False)
      # Set the chosen password
      new_user.set_password(user_form.cleaned_data['password1'])
      # Save the User object
      new_user.save()
      return render(request, 'register_done.html', {'new_user': new_user})
  else:
    user_form = UserRegistrationForm()
    return render(request, 'register.html', {'user_form': user_form})


@login_required
def myprofile(request):
  profile = Profile.objects.get(user=request.user)
  form = ProfileModelForm(data=request.POST or None, files=request.FILES or None, instance=profile)

  if request.method == 'POST':
    if form.is_valid():
      form.save()
      messages.success(request, 'Your profile has been updated successfully!')

  context = {
    'profile': profile,
    'form': form,
  }
  return render(request, 'profiles/myprofile.html', context)


@login_required
def inivites_received(request):
  profile = Profile.objects.get(user=request.user)
  qs = Relationship.objects.invitations_received(profile)
  results = list(map(lambda x:x.sender, qs))
  is_empty = False
  if len(results) == 0:
    is_empty = False
  context = {
    'qs': results,
    'is_empty': is_empty
  }
  return render(request, 'profiles/my_invites.html', context)


@login_required
def accept_invitation(request):
  if request.method == 'POST':
    pk = request.POST.get('profile_pk')
    sender = Profile.objects.get(pk=pk)
    receiver = Profile.objects.get(user=request.user)
    rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
    if rel.status == 'send':
      rel.status = 'accepted'
      rel.save()
      messages.success(request, f"You and {sender.user} are now friends with each other.")
  return redirect('profiles:my-invites')

@login_required
def reject_invitation(request):
  if request.method == 'POST':
    pk = request.POST.get('profile_pk')
    receiver = Profile.objects.get(user=request.user)
    sender = Profile.objects.get(pk=pk)
    rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
    rel.delete()
    messages.info(request, f"You have rejected {sender.user}'s friend request")
  return redirect('profiles:my-invites')


@login_required
def inivite_profiles_list(request):
  user = request.user
  qs = Profile.objects.get_all_profiles_to_invite(user)

  context = {'qs':qs}
  return render(request, 'profiles/to_invite_list.html', context)


@login_required
def profiles_list(request):
  user = request.user
  qs = Profile.objects.get_all_profiles(user)
  context = {
    'qs': qs
  }
  return render(request, 'profiles/profile_list,html', context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
  model = Profile
  template_name = 'profiles/detail.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    user = User.objects.get(username__iexact=self.request.user)
    profile = Profile.objects.get(user=user)
    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)
    rel_receiver = []
    rel_sender = []
    for item in rel_r:
      rel_receiver.append(item.receiver.user)
    for item in rel_s:
      rel_sender.append(item.sender.user)
    context['rel_receiver'] = rel_receiver
    context['rel_sender'] = rel_sender
    context['posts'] = self.get_object().get_all_authors_posts()
    context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
    return context


class ProfileListView(LoginRequiredMixin, ListView):
  model = Profile
  template_name = 'profiles/profile_list.html'

  def get_queryset(self):
    qs = Profile.objects.get_all_profiles(self.request.user)
    return qs

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    user = User.objects.get(username__iexact=self.request.user)
    profile = Profile.objects.get(user=user)
    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)
    rel_receiver = []
    rel_sender = []
    for item in rel_r:
      rel_receiver.append(item.receiver.user)
    for item in rel_s:
      rel_sender.append(item.sender.user)
    context["rel_receiver"] = rel_receiver
    context["rel_sender"] = rel_sender
    context['is_empty'] = False
    if len(self.get_queryset()) == 0:
      context['is_empty'] = True

    return context


@login_required
def send_invitation(request):
  if request.method == 'POST':
    pk = request.POST.get('profile_pk')
    user = request.user
    sender = Profile.objects.get(user=user)
    receiver = Profile.objects.get(pk=pk)

    rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
    messages.success(request, f'Friend request sent to {receiver.user}')
    return redirect(request.META.get('HTTP_REFERER'))
  return redirect('profiles:myprofile')


@login_required
def remove_from_friends(request):
  if request.method == 'POST':
    pk = request.POST.get('profile_pk')
    user = request.user
    sender = Profile.objects.get(user=user)
    receiver = Profile.objects.get(pk=pk)

    rel = Relationship.objects.get(
      (Q(sender=sender) & Q(receiver=receiver)) |
      (Q(sender=receiver) & Q(receiver=sender))
    )
    rel.delete()
    messages.info(request, f'{receiver.user} has been removed from your friends list')

    return redirect(request.META.get('HTTP_REFERER'))
  return redirect('profiles:myprofile')

src/profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
  Profile Detail
{% endblock title %}
  
{% block content %}
  <div class="row">
    <div class="col-12 text-center border-bottom d-flex align-items-start mx-auto mt-2 p-2">
      <img src="{{ object.avatar.url }}" alt="profile_pic" class="rounded-circle" width="80px">
      <h2  class="p-2">{{ object.user }}</h2>
      <div class="p-2">
        Posts
        <div>
          {{ object.get_posts_num }}
        </div>
      </div>
      <div  class="p-2">
        Likes given
        <div>{{ object.get_likes_given_num }}</div>
      </div>
      <div class="p-2">
        Likes received
        <div>{{ object.get_likes_received_num }}</div>
      </div>
      <div class="p-2">
        Friends
        <div>{{ object.get_friends_num }}</div>
      </div>
      
      {% if object.user not in rel_receiver and object.user not in rel_sender %}
        <div class="p-2">
          <form action="{% url 'profiles:send-invite' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value="{{ object.pk }}">
            <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i> Add to friends</button>
          </form>
        </div>
      {% endif %}
      
      {% if object.user in rel_receiver and request.user not in object.friends.all %}
        <button class="btn btn-dark"><i class="fas fa-clock"></i> Waiting for approval</button>
      {% endif %}
      
      {% if request.user in object.friends.all %}
        <div>
          <form action="{% url 'profiles:remove-friend' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value="{{ object.pk }}">
            <button type="submit" class="btn btn-danger" ><i class="fas fa-minus"></i> Remove from friends</button>
          </form>
        </div>
      {% endif %}
    </div>

    <div class="col-12">
      {% if len_posts %}
        {% for post in posts %}
          <ul class="border rounded">
            <li>
              <div class="m-3 mb-0">
                {{ forloop.counter }}
                <span class="float-right"><i class="fas fa-heart"> {{ post.num_likes }}</i> &nbsp; <i class="fas fa-comments"> {{ post.num_comments }}</i> </span>
              </div>
              <div>{{ post.content|linebreaks }}</div>
            </li>
          </ul>
        {% endfor %}
      {% else %}
        <h3>No posts of this user</h3>  
      {% endif %}
    </div>
  </div>
{% endblock content %}

src/profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
  My Invites
{% endblock title %}
  
{% block content %}
  {% for obj in qs %}
    <div class="row m-2">
      <div class="col-2">
        <img class="rounded-circle" width="100px" src="{{ obj.avatar.url }}">
      </div>
      <div class="col-2">
        <h3>{{obj.user}}</h3>
        <p>{{obj.bio}}</p>
      </div>
      <a href="{{ obj.get_absolute_url }}"><button class="btn btn-primary">See profile</button></a>
      <div class="text-center ml-auto">
        <form action="{% url 'profiles:accept-invite' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
          <button type="submit" class="btn btn-success align-middle"><i class="fas fa-check"></i> Accept invite</button>
        </form>
      </div>
      <div class="col-2">
        <form action="{% url 'profiles:reject-invite' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
          <button type="submit" class="btn btn-danger align-middle"><i class="fas fa-times"></i> Reject invite</button>
        </form>

      </div>
    {% empty %}
      <p class="text-center mt-2"><b>No invitations here...</b></p>  
    </div>
    {% endfor %}
  </div>

{% endblock content %}

src/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  My Profile
{% endblock title %}
  
{% block content %}

  <div class="row">
    <div class="col-xm-12 col-md-4 text-center">
      <img src="{{ profile.avatar.url }}" alt="profile_pic" class="img-thumbnail">

      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Update Profile
      </button>

      <h3 class="mt-2"> My Profile : <i>{{ request.user }}</i></h3>

        <a href="{% url 'password_change' %}" class="btn btn-warning m-2">Change your password</a>
    </div>

    <div class="col-xm-12 col-md-8">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <td scope="col">Username</td>
            <td>{{ profile.user }}</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td scope="col">First Name</td>
            <td>{{ profile.first_name }}</td>
          </tr>
          <tr>
            <td scope="col">Last Name</td>
            <td>{{ profile.last_name }}</td>
          </tr>
          <tr>
            <td scope="col">Bio</td>
            <td>{{ profile.bio }}</td>
          </tr>
          <tr>
            <td scope="col">Number of friends</td>
            <td>{{ profile.get_friends_num }}</td>
          </tr>
          <tr>
            <td scope="col">Friends</td>
            <td>
              <ul>                
                {% for friend in profile.get_friends %}
                  <li>{{ friend }}</li>                  
                {% endfor %}                  
              </ul>
            </td>
          </tr>
          <tr>
            <td scope="col">Number of posts</td>
            <td>{{ profile.get_posts_num }}</td>
          </tr>
          <tr>
            <td scope="col">Number of likes given</td>
            <td>{{ profile.get_likes_given_num }}</td>
          </tr>
          <tr>
            <td scope="col">Number of likes received</td>
            <td>{{ profile.get_likes_received_num }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Update Your Profile</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="text-center mb-3">            
            <i class="text-center">Provide some additional/newest info about you </i>
          </div>
          <div class="row">            
            <div class="col-4">
              <img src="{{ profile.avatar.url }}" alt="profile_pic" class="w-100">
            </div>
            <div class="col-8">
              <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="modal-footer">
                  <button type="submit" class="btn btn-success">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
          
      </div>
    </div>
  </div>
{% endblock content %}

src/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
  All Profiles
{% endblock title %}

{% block content %}
  {% if is_empty %}
    <h1>No profiles to interact with</h1>
  {% endif %}

  {% for obj in object_list %}
    <div class="row m-2">
      <div class="col-2">
        <img class="rounded-circle" width="100px" src="{{ obj.avatar.url }}">
      </div>
      <div class="col-4">
        <h3>{{obj.user}}</h3>
        <p>{{obj.bio}}</p>
      </div>
      <a href="{{ obj.get_absolute_url }}"><button class="btn btn-primary">See profile</button></a>
      <div class="col-4">
        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
          <form action="{% url 'profiles:send-invite' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value={{obj.pk}}>
            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Add to friends</button>
          </form>
        {% endif %}

        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
          <button class="btn btn-dark"><i class="fas fa-clock"></i> Waiting for approval</button>
        {% endif %}

        {% if request.user in obj.friends.all %}
          <form action="{% url 'profiles:remove-friend' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value={{obj.pk}}>
            <button type="submit" class="btn btn-danger"><i class="fas fa-minus"></i> Remove from friends</button>
          </form>
        {% endif %}
      </div>
    </div>
    <div class="col-2"></div>
    {% endfor %}
  </div>
{% endblock content %}

src/profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
  Invites Friends
{% endblock title %}
  
{% block content %}
  {% if is_empty %}
    <h1>No invitations here...</h1>
  {% endif %}

  {% for obj in qs %}
    <div class="row mt-2">
      <div class="">
        <img class="rounded-circle" width="100px" src="{{ obj.avatar.url }}">
      </div>
      <div class="col">
        <h3>{{obj.user}}</h3>
        <p>{{obj.bio}}</p>
      </div>
      <div class="col">        
        <a href="{{ obj.get_absolute_url }}"><button class="btn btn-primary">See profile</button></a>
      </div>

      <div class="text-center ml-auto">
        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
          <form action="{% url 'profiles:accept-invite' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Accept invite</button>
          </form>
        {% endif %}
      </div>

      {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
        <button class="btn btn-dark"><i class="fas fa-clock"></i> Waiting for approval</button>
      {% endif %}
          
      <div class="col">
        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
          <form action="{% url 'profiles:reject-invite' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
            <button type="submit" class="btn btn-danger"><i class="fas fa-times"></i> Reject invite</button>
          </form>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock content %}