src/posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
  path('search/', views.search, name='search'),
  path('', views.post_comment_create_and_list_view, name='main-post-view'),
  path('myposts/', views.myposts, name='myposts'),
  path('liked/', views.like_unlike_post, name='like-post-view'),
  path('<pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
  path('<pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
]

src/profiles/urls.py
from django.urls import path
from .import views

app_name = 'profiles'

urlpatterns = [
  path('', views.ProfileListView.as_view(), name='all-profiles'),
  path('myprofile/', views.myprofile, name='myprofile'),
  path('my-invites/', views.inivites_received, name='my-invites'),
  path('to-invite/', views.inivite_profiles_list, name='invite-profiles'),
  path('send-invite/', views.send_invitation, name='send-invite'),  
  path('remove-friend/', views.remove_from_friends, name='remove-friend'),
  path('my-invites/accept/', views.accept_invitation, name='accept-invite'),
  path('my-invites/reject/', views.reject_invitation, name='reject-invite'),
  path('<slug>/', views.ProfileDetailView.as_view(), name='profile-detail'),
]

src/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from profiles.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),  
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('register/', register, name='register'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Social {% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    
    <div class="container">      
      {% if messages %}        
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>  
        {% endfor %}          
      {% endif %}
              
      {% block content %}
      {% endblock content %}
    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js" integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ==" crossorigin="anonymous"></script>
    {% block extrajs %} 
    {% endblock extrajs %}
  </body>
</html>

src/templates/navbar.html
{% url 'login' as path_to_login %}
{% url 'logout' as path_to_logout %}
{% url 'register' as path_to_register %}

{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:myposts' as path_to_myposts %}
{% url 'profiles:myprofile' as path_to_my_profile %}
{% url 'profiles:my-invites' as path_to_my_invites %}
{% url 'profiles:invite-profiles' as path_to_invites %}
{% url 'profiles:all-profiles' as path_to_all_profiles %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'posts:main-post-view' %}">Social</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      {% if request.path == path_to_home %}active{% endif %}
      <li class="nav-item {% if request.path == path_to_posts %}active{% endif %}">
        <a class="nav-link" href="{{ path_to_posts }}">Home</a>
      </li>
      <li class="nav-item {% if request.path == path_to_myposts %}active{% endif %}">
        <a href="{{ path_to_myposts }}" class="nav-link">My Posts</a>
      </li>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Friends
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ path_to_all_profiles }}">All Profiles</a>
          <a class="dropdown-item" href="{{ path_to_invites }}">Send Invites</a>
          <a class="dropdown-item" href="{{ path_to_my_invites }}">Received Invites &nbsp; <span class="badge badge-primary">{{invites_num}}</span></a>
        </div>
      </li>
      
      <form class="form-inline ml-2" action="{% url 'posts:search' %}" method="GET">
        <input class="form-control mr-sm-2" type="search" placeholder="Search here..." name='q' aria-label="Search">
        <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>

    
    
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}      
        <li class="nav-item {% if request.path == path_to_my_profile %}active{% endif %}">          
          <a class="nav-link" href="{{ path_to_my_profile }}">
            <img src={{picture.url}} class="rounded-circle" width="40px"> Welcome, {{ request.user }}
          </a>
        </li>
        <li class="nav-item {% if request.path == path_to_logout %}active{% endif %}">
          <a class="nav-link" href="{{ path_to_logout }}">logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.path == path_to_login %}active{% endif %}">
        <a class="nav-link" href="{{ path_to_login }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == path_to_register %}active{% endif %}">
          <a class="nav-link" href="{{ path_to_register }}">Register</a>
        </li>
      {% endif %}

    </ul>
  </div>
</nav>

src/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create an account{% endblock %}

{% block content %}
  <h1>Create an account</h1>
  <p>Please, sign up using the following form:</p>

  <form method="post">
    {{ user_form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account" class="btn btn-secondary"></p>
  </form>
{% endblock %}

src/templates/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
  <h1>Welcome {{ new_user.first_name }}!</h1>
  <p>Your account has been successfully created. Now you can <a href="{% url 'login' %}">log in</a>.</p>
{% endblock %}

src/templates/search.html
{% extends 'base.html' %}

{% block title %}
  Search Results
{% endblock title %}
  
{% block content %}
  <h2>Results matching to '{{ q }}'</h2>

  <h4 class="border-bottom border-dark">Profiles</h4>

  {% for obj in profiles %}
    <div class="row mt-2">
      <div class="col-2">
        <img class="rounded-circle" width="100px" src="{{ obj.avatar.url }}">
      </div>
      <div class="float-right col-8">        
        <h3>{{obj.user}}</h3>        
        {% if obj.first_name %}
          <span>          
            First Name: {{ obj.first_name }}
          </span>
        {% endif %}
        {% if obj.last_name %}
          <span>          
            Last Name: {{ obj.last_name }}
          </span>
        {% endif %}
          
        <span>Bio: {{obj.bio}}</span>
      </div>
      <a href="{{ obj.get_absolute_url }}"><button class="btn btn-primary mx-auto text-center">See profile</button></a>
    </div>  
  {% empty %}
    <p>No Profiles match with given query</p>
  {% endfor %}
  
  <h4 class="border-bottom border-dark">Posts</h4>
  {% for obj in posts %}
    <div class="row">
      <div class="col-12 border">       
        <div class="p-2 float-right">
          <h3 class="">          
            <img class="rounded-circle" width="100px" src="{{ obj.author.avatar.url }}">
            {{ obj.author.user }}
          </h3>
        </div>
        {{ obj.content|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>No posts match with given query</p>  
  {% endfor %}
    
{% endblock content %}