src/posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [
  path('search/', views.search, name='search'),
  path('', views.post_comment_create_and_list_view, name='main-post-view'),
  path('myposts/', views.myposts, name='myposts'),
  path('liked/', views.like_unlike_post, name='like-post-view'),
  path('<pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
  path('<pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
]

src/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from profiles.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),  
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('register/', register, name='register'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
from sorl.thumbnail import ImageField

class PublishManager(models.Manager):
  def get_queryset(self):
    queryset = super().get_queryset().filter(draft=False)
    return queryset

class Post(models.Model):
  content = models.TextField()
  image   = ImageField(upload_to='posts/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
  liked   = models.ManyToManyField(Profile, blank=True, related_name='likes')
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)
  author  = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
  draft   = models.BooleanField(default=False)

  objects = models.Manager()
  published = PublishManager()

  def __str__(self):
    return str(self.content[:20])

  def num_likes(self):
    return self.liked.all().count()
  
  def num_comments(self):
    return self.comments.all().count()

  class Meta:
    ordering = ('-created', )
  

class Comment(models.Model):
  user    = models.ForeignKey(Profile, on_delete=models.CASCADE)
  post    = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
  body    = models.TextField(max_length=300)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f"comment on post:'{self.post}' by '{self.user}' -- {self.pk}"

LIKE_CHOICES = (
  ('Like', 'Like'),
  ('Unlike', 'Unlike'),
)

class Like(models.Model):
  user    = models.ForeignKey(Profile, on_delete=models.CASCADE)
  post    = models.ForeignKey(Post, on_delete=models.CASCADE)
  value   = models.CharField(choices=LIKE_CHOICES, max_length=8)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f"{self.user}-{self.post}-{self.value}"

src/posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
  content = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))

  class Meta:
    model = Post
    fields = ('content', 'image', 'draft')


class CommentModelForm(forms.ModelForm):
  body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))

  class Meta:
    model = Comment
    fields = ('body', )

src/posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm, CommentModelForm
from django.views.generic import ListView, UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

# search function -> search in profile(fields: first_name, last_name, user)
# posts(fields: contett, author)

def search(request):
  q = request.GET.get('q', None)
  print(q)
  if q is not None:
    all_model_dict = {
      'profiles' : Profile.objects.filter(
        Q(first_name__icontains=q) | Q(last_name__icontains=q) | Q(user__username__icontains=q)
      ), 
      'posts': Post.objects.filter(
        Q(content__icontains=q) | Q(author__user__username=q)
      ),
      'q': q,
    }
  else:
    all_model_dict = {}
  print(all_model_dict)
  return render(request, 'search.html', all_model_dict)

@login_required
def myposts(request):
  profile = Profile.objects.get(user=request.user)
  qs = Post.objects.filter(author=profile)
  context = {
    'qs': qs,
    'profile':profile,
  }
  return render(request, 'posts/myposts.html', context)

@login_required
def post_comment_create_and_list_view(request):
  qs = Post.published.all()
  profile = Profile.objects.get(user=request.user)

  # initial data
  p_form = PostModelForm()
  c_form = CommentModelForm()

  profile = Profile.objects.get(user=request.user)

  if 'submit_p_form' in request.POST:
    p_form = PostModelForm(request.POST, request.FILES)
    if p_form.is_valid():
      instance = p_form.save(commit=False)
      instance.author = profile
      messages.success(request, 'Your post has been added.')
      instance.save()
      p_form = PostModelForm()
  
  if 'submit_c_form' in request.POST:
    c_form = CommentModelForm(request.POST)
    if c_form.is_valid():
      instance = c_form.save(commit=False)
      instance.user = profile
      instance.post = Post.objects.get(id=request.POST.get('post_id'))
      messages.success(request, 'Your comment has been added.')
      instance.save()
      c_form = CommentModelForm()
  
  context = {
    'qs': qs,
    'profile': profile,
    'p_form': p_form,
    'c_form': c_form,
  }
  return render(request, 'posts/list.html', context)


@login_required
def like_unlike_post(request):
  user = request.user
  if request.method == 'POST':
    post_id = request.POST.get('post_id')
    post_obj = Post.objects.get(id=post_id)
    profile = Profile.objects.get(user=user)

    if profile in post_obj.liked.all():
      post_obj.liked.remove(profile)
    else:
      post_obj.liked.add(profile)

    like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

    if not created:
      if like.value == 'Like':
        like.value = 'Unlike'
      else:
        like.value = 'Like'
    else:
      like.value = 'Like'

      post_obj.save()
      like.save()
  return redirect('posts:main-post-view')

class PostDeleteView(LoginRequiredMixin, DeleteView):
  model = Post
  template_name = 'posts/confirm_delete.html'
  success_url = reverse_lazy('posts:main-post-view')

  def get_object(self, queryset=None):
    pk = self.kwargs.get('pk')
    obj = Post.objects.get(pk=pk)
    if not obj.author.user == self.request.user:
      messages.warning(self.request, 'You need to be the author of the post in order to delete it.')
    return obj


class PostUpdateView(LoginRequiredMixin, UpdateView):
  form_class = PostModelForm
  model = Post
  template_name = 'posts/update.html'
  success_url = reverse_lazy('posts:main-post-view')

  def form_valid(self, form):
    profile = Profile.objects.get(user=self.request.user)
    if form.instance.author == profile:
      messages.info(self.request, 'Your post has been updated successfully')
      return super().form_valid(form)
    else:

      form.add_error(None, "You need to be the author of the post in order to update it")
      return super().form_invalid(form)

src/posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Delete post 
{% endblock title %}
  
{% block content %}
  <h1>Delete Post</h1>
  <form action="." method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete the post ?</p>
    <input type="submit" value="Yes, Delete it" class="btn btn-danger">
    <a href="{% url 'posts:main-post-view' %}" class="btn btn-info">No, take me back</a>
  </form>
{% endblock content %}

src/posts/templates/posts/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Home  
{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-xs-12 col-lg-9 ">
      {% for obj in qs %}
      <div class="border rounded mt-2 p-2">
        <div class="pt-2">
          <div class="">
            <img src="{{ obj.author.avatar.url }}" alt="profile_pic" class="rounded-circle float-left" width="40px">
            <span class="pl-5 mt-2"><b>{{ obj.author.user }} -- {{ obj.created|timesince }} ago </b></span>
            
            {% ifequal request.user obj.author.user %}
              <span class="float-right">
                <a href="{% url 'posts:post-update' obj.pk %}" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>
                <a href="{% url 'posts:post-delete' obj.pk %}" class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i></a>
              </span>
            {% endifequal %}
            <hr class="mb-0">
          </div>
        </div>
        <div class="text-center mt-0">          
          {% if obj.image %}
          <img src="{{ obj.image.url }}" alt="post_image" class="img-thumbnail">
          {% endif %}
        </div>
        
        <div class="px-3">          
          <p class="text-justify">{{ obj.content|linebreaks }}</p>
        </div>
        <div class="float-right">
          <form action="{% url 'posts:like-post-view' %}" method="post" id="{{ obj.id }}" class="like-form">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ obj.id }}">

            <button type="submit" class="like-btn{{ obj.id }} btn btn-info">
              {% if profile not in obj.liked.all %}
                Like
              {% else %}
                Unlike
              {% endif %}
            </button>
            
            <div>
              <div class="like-count{{obj.id}}">{{ obj.num_likes }}                
                <span>like{{ obj.num_likes|pluralize }}</span>
              </div>
            </div>
          </form>
        </div>
        
        <div class="mx-auto">
          <div>
            <i class="fas fa-comments fa-2x"></i>
            <span>{{ obj.num_comments }} comment{{ obj.num_comments|pluralize }} </span>
            
            
            {% if obj.num_comments > 0 %}              
            
            <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample{{obj.pk}}" role="button" aria-expanded="false" aria-controls="collapseExample">
              show / hide comments
            </a>
            {% endif %}
          </div>

          <div class="collapse" id="collapseExample{{obj.pk}}">
            <div class="card card-body">
            {% if obj.comments.all %}
              {% for c in obj.comments.all %}
                <div>
                  <img src="{{ c.user.avatar.url }}" alt="profile_pic" class="rounded-circle float-left" width="30px">
                  <span class=""> {{ c.user|linebreaks }}</span>
                  
                  {% if request.user == obj.author.user %}
                    <span class="">
                      <a href="" class="btn btn-danger">Delete</a>
                    </span>
                  {% endif %}

                  <p>       
                    {{ c.body }}
                    </p>
                  </div>
              {% endfor %}
            {% endif %}
            </div>
          </div>

          <form action="." method="post">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ obj.id }}">
            {{ c_form|crispy }}
            <input type="submit" name="submit_c_form" value="Comment" class="btn btn-primary">
          </form>
        </div>
      </div>

      {% endfor %}
    </div>


    <div class="col-sm-12 col-lg-3">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ p_form|crispy }}
        <input type="submit" name="submit_p_form" value="Post" class="btn btn-primary">
      </form>
    </div>
    
  </div>
{% endblock content %}


{% block extrajs %}
<script>

  $( document ).ready(function() {
    $('.like-form').submit(function(e){
      e.preventDefault()
      
      const post_id = $(this).attr('id')

      const likeText = $(`.like-btn${post_id}`).text()
      const trim = $.trim(likeText)

      const url = $(this).attr('action')
      
      let res;
      const likes = $(`.like-count${post_id}`).text()
      const trimCount = parseInt(likes)
      
      $.ajax({
        type: 'POST',
        url: url,
        data: {
          'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
          'post_id':post_id,
        },
        success: function(response) {
          console.log('sdsd');
          if(trim === 'Unlike') {
            $(`.like-btn${post_id}`).text('Like')
            res = trimCount - 1
          } else {
            $(`.like-btn${post_id}`).text('Unlike')
            res = trimCount + 1
          }

          $(`.like-count${post_id}`).text(res);
        },
        error: function(response) {
          console.log('error', response);
        }
      })

    })
  });
</script>
{% endblock extrajs %}  

src/posts/templates/posts/myposts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Home  
{% endblock title %}

{% block content %}
  <div class="row">
    {% for obj in qs %}
      <div class="col-6">
        <div class="border rounded mt-2 p-2">
          <div class="pt-2">
            <div>
              <span><b>{{ obj.created|timesince }} ago </b></span>
              
              {% if obj.draft %}
                <span class="text-danger"><b><i>&nbsp; Status: Draft / Not published </i> </b> </span>
              {% endif %}
                
              {% ifequal request.user obj.author.user %}
                <span class="float-right">
                  <a href="{% url 'posts:post-update' obj.pk %}" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>
                  <a href="{% url 'posts:post-delete' obj.pk %}" class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i></a>
                </span>
              {% endifequal %}
              <hr class="mb-0">
            </div>
          </div>
          <div class="text-center mt-0">          
            {% if obj.image %}
            <img src="{{ obj.image.url }}" alt="post_image" class="img-thumbnail">
            {% endif %}
          </div>
          
          <div class="px-3">          
            <p class="text-justify">{{ obj.content|linebreaks }}</p>
          </div>
          <div class="float-right">
            <div>
              <div class="like-count{{obj.id}}">{{ obj.num_likes }}                
                <span>like{{ obj.num_likes|pluralize }}</span>
              </div>
            </div>
          </div>
          
          <div class="mx-auto">
            <div>
              <i class="fas fa-comments fa-2x"></i>
              <span>{{ obj.num_comments }} comment{{ obj.num_comments|pluralize }} </span>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
    <div class="col mt-2">
      <p class="text-center"><b> You haven't added any post yet.</b></p>
    </div>
    {% endfor %}
    
  </div>
{% endblock content %}

src/posts/templates/posts/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Update Post
{% endblock title %}
  
{% block content %}
  <h1 class="border-bottom text-center">Update Post</h1>
  <div>
    <form action="" method="post">
      {{ form|crispy }}
      {% csrf_token %}
      <input type="submit" value="Update" class="btn btn-success">
    </form>
  </div>
  
{% endblock content %}